### ISSUE TITLE
Conditional formatting with repeated column names

### ISSUE THREAD

**Issue by DanaJomar** [LyzandeR/tableHTML#23]
Conditional formatting does not return the right result when using  `headers` to give  the columns the same string as a name.

An example to reproduce the problem:
(please un-comment `headers` to see the other result)

```r
library(dplyr)
library(tableHTML)

set.seed(345)
df <- data.frame(a = sample(1:100, 20), b = sample(1:100, 20), c = sample(1:100, 20))


tableHTML(df,
          # headers = rep('col', ncol(df)),
          rownames = FALSE,
          widths = rep(50, ncol(df)), 
          theme = 'scientific') %>%
  add_css_conditional_column(conditional = '<', value = 10,
                             css = list('background-color', 'red'),
                             columns = c(1:ncol(df))) 

```

**Comment by clemens-zauchner** [comment]
Thank you very much for submitting the issue. I have had a look and it seems to be a bug. 

In the `add_css_conditional_column()` function, a named list `condition` of logical values for each column is created. This `condition` list is then subsetted using the headers of the `tableHTML`. If all columns have the same name, it will return the first element of the list for all columns.

There seems to be an easy fix, by using the column index instead of the name for subsetting.

i.e. replacing 
`replace_style(tableHTML, split = paste0('id="tableHTML_column_', i, '"'),
                                 style[[attributes$headers[i]]],
                                 condition[[attributes$headers[i]]])`

with:

`replace_style(tableHTML, split = paste0("id=\"tableHTML_column_", 
                                                           i, "\""), style[[i]], condition[[i]])`
