### ISSUE TITLE
tableHTML_to_image() plot overlay

### ISSUE THREAD

**Issue by clemens-zauchner** [LyzandeR/tableHTML#26]
If you use `tableHTML_to_image()` with a plot in the pane, the function will add the second tableHTML over that plot:

`plot(1:5)`
`mtcars %>% tableHTML(theme = 'rshiny-blue') %>% tableHTML_to_image()`

will result in this:
![output_1](https://user-images.githubusercontent.com/29435287/49808298-84b3e200-fd5c-11e8-8308-499f60c34264.JPG)

If you use the function twice, the second tableHTML will be shown on top of the first one: 
` iris %>% head() %>% tableHTML() %>% tableHTML_to_image(zoom = 2)`
` mtcars %>% tableHTML() %>% tableHTML_to_image(zoom = 2)`

![output_2](https://user-images.githubusercontent.com/29435287/49808637-49fe7980-fd5d-11e8-81ab-569aac135413.png)

**Comment by LyzandeR** [comment]
Hmmmm. Good find.

I am not sure what to do about this. I am thinking about leaving it as it is, giving the complete control to the user to do `dev.off()` on their own, instead of somehow invoking it ourselves...

The alternative would be for us to run it at the beginning of the function so if any image / plot is already displayed to remove it before plotting. Maybe I could add an argument `add`? If it is `TRUE` then the `dev` windows stay open, otherwise they get deleted.

What do you think?

**Comment by clemens-zauchner** [comment]
resolved with PR #27
