### ISSUE TITLE
Awesome! But one (small, I hope) bug

### ISSUE THREAD

**Issue by johnfrombluff** [LyzandeR/tableHTML#3]
Thank you, thank you, thank you! This is just what I have been looking for, for a *long* time. I have spotted a small bug, which I hope will be easy to fix. When calling tableHTML with no non-optional arguments, the columns are aligned correctly, i.e. flush left, and aligned on the decimal point. However when using the 'scientific' theme, which is otherwise **superb**, the vertical alignment is altered, i.e. the alignment has been changed to centred. Is this a bug, or is there a way to alter the scientific them in user space?

Thanks again for this great package,

John

**Comment by LyzandeR** [comment]
Hi John,

Thanks a lot for your really kind words. It feels really nice to know that my work is appreciated, so thank you.

Now let's go to the problem you describe:

Both of the two themes provided in the package (which hopefully will increase in the future) use the `add_css_*` family of functions within the `tableHTML` function. Therefore, any changes you see from the default theme are actually intended. When using the argument `theme = 'scientific'` internally ` add_css_column(css = list('text-align', 'center'), column_names = names(obj))` is called which aligns the columns to the center. The full code that shows all the css styling of the scientific theme can be found between lines 410-432 in tableHTML.R.

Of course I appreciate that different users will need different css stylings in the themes. In order to modify the scientific theme there are two routes you can take. One is to simply copy the wanted parts of the `add_css_*` functions from the lines above and basically design the styling yourself or you could use `replace_html` to specifically convert the part that aligns the columns to center into a left align.

i.e. something like this should do the trick:

```
tableHTML(mtcars, widths = c(140, rep(50, 11)), theme = 'scientific') %>% 
   replace_html('text-align:center', 'text-align:left', replace_all = TRUE)
```

Hope that helps. If not I would kindly ask you to provide a small piece of code that replicates the problem so that it can be easier for me to visualize it.

Thanks again for your kind words.

Regards,
Theo

**Comment by johnfrombluff** [comment]
Thanks Theo! And, you're welcome :-)
