### ISSUE TITLE
right justify numbers in a table

### ISSUE THREAD

**Issue by smithjd** [LyzandeR/tableHTML#5]
I can't see a way to right justify numbers in a table.  Does tableHTML provide for that kind of thing?  The examples suggest not:
![screen shot 2017-04-24 at 3 01 05 pm](https://cloud.githubusercontent.com/assets/2738096/25360697/10bf5d8a-28ff-11e7-99f5-7ac11463adf7.jpg)

I would like an option to right-justify a column like the hp column.  Is there a work-around?

**Comment by LyzandeR** [comment]
`tableHTML` is used for the HTML code. If you want to beautify (or in general change how the table looks) the table you need to use the `add_css_*` family of functions. These functions are explained in detail in the [tutorial](https://cran.r-project.org/web/packages/tableHTML/vignettes/tableHTML.html) So, in order to right justify the `hp` column for example, you would use `add_css_column`:

```{r}
library(tableHTML)
mtcars %>%
 tableHTML() %>%
 add_css_column(list('text-align', 'right'), column_names = 'hp')
```
Hope this helps!

**Comment by smithjd** [comment]
Thank you!  I suggest that that is such a common use-case that it should be moved up in prominence.  It slipped right by me.
