### ISSUE TITLE
tableHTML output when using pipes inside function

### ISSUE THREAD

**Issue by buke-phalos** [LyzandeR/tableHTML#6]
I have used the function tableHTML and as obj I have used a data.frame that I have created by grouping and summarising (using dplyr). The class of the resulting structure is data.frame, but the output is not as expected (see screenshot below).

test_df <- data.frame(week = c(1, 1, 2, 3, 4))

tableHTML::tableHTML(
  test_df %>% 
    group_by(week) %>% 
    summarise(n = n()) %>%
    as.data.frame,
  theme = 'rshiny-blue',
  rownames = FALSE
  )

![image](https://cloud.githubusercontent.com/assets/20457996/26410421/28a55cde-409b-11e7-80cc-a64a03996bda.png)

However, if you save the data frame and then use the function on it, it works.

test_df_grouped <- test_df %>% 
  group_by(week) %>% 
  summarise(n = n()) %>%
  as.data.frame

tableHTML::tableHTML(
 test_df_grouped,
  theme = 'rshiny-blue',
  rownames = FALSE
)

**Comment by LyzandeR** [comment]
This is caused because of `deparse(subsitute(...` at the beginning of the code where usually the name of the data.frame becomes the class of the table as well. Since, you are not passing the data.frame directly but a call, that gets converted into the class name. However, the `%>%` operator has the `>` character which closes the table tag when the table gets created.

 I will need to change that in the next version by not using  `deparse(subsitute(...` anymore.

For now just run the dplyr chain call outside `tableHTML` and then run `tableHTML` on the data.frame:

```{}
test_df %>%
 group_by(week) %>%
 summarise(n = n()) %>%
 as.data.frame,

tableHTML::tableHTML(
 test_df,
 theme = 'rshiny-blue',
 rownames = FALSE
)
```

**Comment by LyzandeR** [comment]
Version 1.0.1 is out on CRAN and address this issue.
