### ISSUE TITLE
href in a column

### ISSUE THREAD

**Issue by smithjd** [LyzandeR/tableHTML#8]
Is there a way to have a column include actual HTML links?  I'm trying to create a table that has URLs in it.  Something like:

`<a href="http://some.url.com">go here</a>`

What I get in the output html, however, is something like:

`&#60;a href="http://some.url.com"&#62;go here&#60;/a&#62;`

**Comment by LyzandeR** [comment]
Hi John,

Thanks for the message. 

I added HTML escapes on the latest version of `tableHTML` because people noticed that when using `<` or `>` in their tables, HTML tags would open (or close) before (or after) they had to and they missed part of the text in the table. However, as you found out, yours is a very legit case where the URLs should not be escaped.

I will probably include this in the new version as an argument, so the user has full control on escaping `>` or `<`. In the meantime you can use this to convert the escapes:

```{r]
df <- data.frame(col1 = '<a href="http://some.url.com">go here</a>')
tableHTML(df) %>%
 replace_html(pattern = '&#60;', '<', replace_all = TRUE) %>%
 replace_html(pattern = '&#62;', '>', replace_all = TRUE)
```

<table style="border-collapse:collapse;" class=table_7059 border=1>
<thead>
<tr>
  <th id="tableHTML_header_1"> </th>
  <th id="tableHTML_header_2">col1</th>
</tr>
</thead>
<tbody>
<tr>
  <td id="tableHTML_rownames">1</td>
  <td id="tableHTML_column_1"><a href="http://some.url.com">go here</a></td>
</tr>
</tbody>
</table>

Hope it helps.
Theo

**Comment by smithjd** [comment]
That's a very good solution.  Thanks!

**Comment by LyzandeR** [comment]
Version 1.1.0 is out.
